### ISSUE TITLE
Can't install repackaged artifacts if they have already been installed

### ISSUE THREAD

**Issue by aloubyansky** [ppalaga/repackage-tests-maven-plugin#2]
The issue is that the plugin can only be run once for a given artifact. Which makes re-building the project impossible w/o cleaning the local maven repo first.
If there a reason the Maven install request not used to install the repackaged JARs?

**Comment by ppalaga** [comment]
"can only be run once" means (a) that the second invocation results in an error (which?) or that (b) the second invocation does nothing?

**Comment by ppalaga** [comment]
Is this happening with a snapshot version of test-jar dependency?

**Comment by aloubyansky** [comment]
It complains that the file already exists. I was testing only the snapshot versions, yes.

**Comment by ppalaga** [comment]
Thanks, I could reproduce and fix. Let me release ASAP.

**Comment by aloubyansky** [comment]
Excellent, thanks!

**Comment by ppalaga** [comment]
Released 0.3.0. Huh, and it is already there on the Central: http://central.maven.org/maven2/org/l2x6/rpkgtests/rpkgtests-maven-plugin/0.3.0/rpkgtests-maven-plugin-0.3.0.pom
